homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def blog(request):
    return render(request, 'page2.html')

# Create your views here.

homepage/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/logo.ico' %}" />

    <title>Brian | About Me</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <a class="navbar-brand" href="#home">
            <img src="{% static 'images/Logo.png' %}" width="30" height="30" alt="logo" style="margin: 0px 90px 0px 0px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse sticky navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#home" style="margin: 0px 20px">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#about" style="margin: 0px 20px">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#work" style="margin: 0px 20px">Work</a>
            </li>
          </ul>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link" href="#contact" style="margin: 0px 20px">Contact</a>
              </li>
          </ul>
        </div>
      </nav>
  
    <div class="container">

      <!-- HOMEPAGE -->
      <div class="text-center" id = "home" style="padding-top:15vh; max-width: 100%;
      height: auto; position: relative;">
        <h2 class="homeFont">Brian</h2>
        <h3 class="homeFont2">Yudiva</h3>
        <img src="{% static 'images/Myself.png' %}" class="img-fluid" alt="Self" style="width: 120%; height : auto; padding: 5vh;">
          
      </div>

      <!-- ABOUT -->
      <section class = "col" id = "about"> 
            <h1 class="h1Font text-center">ABOUT</h1>
            <h2 class="h2Font text-center">Hi! I’m Brian Athallah Yudiva. Photographer and a student in Computer Science UI.</h2>
      </section>

      <!-- WORK -->
      <section class = "col" id = "work">
        <h1 class="h1Font text-center">WORK</h1>
        <div class="container text-center">
          <div class="row">
            <div class="col-sm">
              <img src="{% static 'images/IMG_9691.jpg' %}" class="img-fluid gallery" alt="IMG_9691">
            </div>
            <div class="col-sm">
              <img src="{% static 'images/IMG_9637.jpg' %}" class="img-fluid gallery" alt="IMG_9637">
              </div>
            <div class="col-sm">
              <img src="{% static 'images/IMG_9717.jpg' %}" class="img-fluid gallery" alt="IMG_9717">
            </div>
          </div>
        </div>
        <div class="text-center" style="margin-top: 2vh">
          <a href="{% url 'homepage:blog' %}" class="aFont">click here</a>
        </div>
      </section>

      <!-- CONTACT -->
      <section class = "col" id = "contact" style="margin-bottom: 15vh;">
          <h1 class="h1Font text-center" style="font-size: 9vw">CONTACT</h1>
          <h3 class="h3Font text-center">email : brian.yudiva@gmail.com</h3>
          <div class="container text-center" style="margin-top: 7vw;">
              <div class="row">
                <div class="col-sm">
                  <a href="https://www.facebook.com/brianathallah.yudiva" target="_blank">
                    <img src="{% static 'images/Facebook.png' %}" class="svgStyle" alt="Facebook">
                  </a>
                </div>
                <div class="col-sm">
                  <a  href="https://www.instagram.com/brianyudiva/?hl=en" target="_blank">
                    <img src="{% static 'images/Instagram.png' %}" class="svgStyle" alt="Instagram">
                  </a>
                  </div>
                <div class="col-sm">
                  <a href="https://www.linkedin.com/in/brian-athallah-y-b81869114/" target="_blank">
                    <img src="{% static 'images/LinkedIn.png' %}" class="svgStyle" alt="LinkedIn">
                  </a>
                </div>
              </div>
            </div>
      </section>
    </div>
        

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/page2.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/logo.ico' %}" />

    <title>Brian | About Me</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <a class="navbar-brand" href="{% url 'homepage:index' %}#home">
            <img src="{% static 'images/Logo.png' %}" width="30" height="30" alt="logo" style="margin: 0px 90px 0px 0px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse sticky navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:index' %}#home" style="margin: 0px 20px">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:index' %}#about" style="margin: 0px 20px">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:index' %}#work" style="margin: 0px 20px">Work</a>
            </li>
          </ul>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:index' %}#contact" style="margin: 0px 20px">Contact</a>
              </li>
          </ul>
        </div>
      </nav>
      <div class="container">
        <section class = "col" id = "about" style="padding-top:5vh"> 
          <h1 class="h1Fontpage2 text-center">things i do now</h1>
          <h2 class="h2Fontpage2 text-center">VPIC of Documentation PMB 2019</h2>
          <h2 class="h2Fontpage2 text-center">Staff of Seminar COMPFEST 11</h2>
          <h2 class="h2Fontpage2 text-center">Staff of LO OH FASILKOM 2019</h2>
        </section>
      </div>
      
  </body>